name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.5'

    steps:
    - uses: actions/checkout@v3
    - name: Set parser lib
      run: export RUBYOPT="-I$(bundle show parser)/lib"
    - name: Install RSpec
      run: gem install rspec
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: rspec
