name: Build

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    strategy:
      matrix:
        ruby:
          - '3.0.5'

    steps:
    - uses: actions/checkout@v3
    - name: Install RSpec
      run: sudo gem install rspec
    - name: Install parser
      run: sudo gem install parser
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: rspec
